### ISSUE TITLE
То вижу, то не вижу накладную за сегодня

### ISSUE THREAD

**Issue by sanyam** [proekt111/gifts.ru-2-1C#1]
Сегодня попробовали загрузить Накладную при помощи вашей обработки. 

При первой загрузки обработки после ввода реквизитов доступа и нажатия "Скачать данные" вроде бы увидел счет и накладную за сегодня (за 17.05.2018). 
Но затем выбрал склад и нажав еще раз кнопку "Скачать данные" - увидел что счет и накладная за сегодня почему-то пропали. 
Загрузить накладную за сегодня так и не удалось
Скриншот текущего состояния прикладываю.
![1c 111](https://user-images.githubusercontent.com/327340/40166059-499272f2-59c6-11e8-92d1-304c704a1439.jpg)

**Comment by dumbuzz** [comment]
Исправлено.
